require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/rubocop'
    - 'bin/rspec'

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 12
