name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2, 3.3, 3.4]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bundle exec rspec
